# Batch 4: images 17-21
REGIONS = {17:(65,280,1415,1270,'spread'), 18:(495,385,915,1075,'portrait'), 19:(45,285,1455,1285,'spread'),
           20:(5,5,1470,900,'spread'), 21:(0,0,650,592,'spread')}
ENTRIES = {
17: [
 ('date_header','title left + date write-in',(100,325,660,380),'Very large title at left; "Date:" write-in with the date handwritten above a line.',{}),
 ('weekday_circles','M T W T F S S with circles (tick today)',(478,340,660,383),'Seven letters over hollow circles; a check marks the day.',{}),
 ('sorted_task_hub','3x4 colour-coded zones of 5 checkbox lines each',(808,378,1380,1225),'Twelve labelled zones: call, email, text, do today, appointments, follow up on, do soon, schedule, research, today\'s wins, buy, random thoughts. Each coloured and edge-defined with five checkbox lines.',{'sens+':'Colour blocks make zones clear but 12 zones is a lot.'}),
 ('appointments','tinted panel: time column + write-in lines',(292,601,477,810),'Orange panel with five rows, each with a time colon and write-in line.',{}),
 ('to_buy','tinted panel: checkbox lines',(297,1025,480,1232),'Lilac panel with checkbox lines.',{}),
 ('wins','open box (today\'s wins)',(108,1025,296,1232),'Unruled box for free-hand wins.',{}),
 ('brain_dump','random thoughts: open box',(484,1022,672,1230),'Unruled box labelled "random thoughts".',{}),
],
18: [
 ('month_year_strip','colour months + 1-31 + mood face',(500,390,912,425),'Rainbow month bar over days 1-31, weekday letters, a smiley mood circle at the end.',{'sens+':'Very small and busy.'}),
 ('brain_dump','labelled open box (dump everything, no judging)',(500,435,795,545),'Pale box with a caption encouraging a no-judgement dump.',{}),
 ('not_to_do','4 grey checkbox lines',(800,435,912,545),'Small grey box with four checkbox lines.',{}),
 ('top_priorities','yellow panel: 3 lines + rating icons + reward',(500,548,912,658),'Priorities header; three lines with a rating-icon strip (check / traffic light / energy) and a reward line.',{'draw':3,'sens+':'Icon strips add complexity.'}),
 ('secondary_tasks','pink "do later": 3 tasks each with sub-steps + icons',(500,662,912,825),'Three tasks each with sub-step arrows and rating strip, reward line at bottom.',{'draw':3}),
 ('secondary_tasks','purple "everything else": 5 checkboxes + reward',(500,827,760,970),'Five checkbox lines with a reward line.',{}),
 ('notes','small boxed notes',(762,827,912,970),'Purple-headed box for notes.',{}),
 ('wins','tinted box (today\'s win, big or small)',(500,978,912,1048),'Open tinted box with a caption.',{}),
 ('tomorrow_first_step','labelled dotted line',(500,1053,912,1072),'One labelled dotted line.',{}),
],
19: [
 ('month_year_strip','colour months + 1-31 + mood face',(112,365,697,410),'Rainbow month bar over days 1-31 with a mood circle.',{'sens+':'Very small and busy.'}),
 ('brain_dump','large tinted box',(112,420,550,570),'Large mint box "dump everything here. No sorting, no judging."',{}),
 ('not_to_do','4 grey checkbox lines',(550,420,697,570),'Small side box.',{}),
 ('one_three_five','1 focus task + 5 "start with" steps with timers',(112,575,697,765),'Yellow panel: single focus task with rating icons and reward; right side lists five start-with steps each with timer circle and checkbox.',{}),
 ('one_three_five','3 support tasks with icon rating strips',(112,768,697,1015),'Pink panel: three tasks with sub-step arrows, icon strips, reward.',{}),
 ('one_three_five','5 tiny wins with icon strips',(112,1022,697,1238),'Purple panel: five round-bullet lines each with a rating strip; reward line.',{}),
 ('wins','tinted box (today\'s win; "this proves my superpower of")',(800,338,1383,418),'Yellow box with a sentence starter.',{}),
 ('people_to_connect','8 icon-bulleted lines',(800,422,1073,580),'Two columns of four lines each with a small friend icon.',{}),
 ('appointments','tinted time + write-in (4 rows)',(800,585,1073,735),'Green panel with four rows, time colons and a colour dot.',{}),
 ('to_buy','tinted panel with 5 checkboxes',(800,740,1073,925),'Yellow panel with five checkboxes.',{}),
 ('energy_tracker','energy & patterns: morning/afternoon/evening + timed notes',(1078,422,1383,885),'Pink-headed panel with three write-in lines and ten time-stamped lines for noting energy shifts.',{'inp':'write-in line','draw':2,'daily':3,'skip':'low','adhd+':'Data-gathering about patterns, not a to-do; helpful but optional.'}),
 ('health_fitness','body check: water / meal / meds / move',(1078,885,1383,925),'Four labelled boxes in one row.',{'adhd+':'Meds box is a visible reminder.'}),
 ('lessons_learned','large open box (what did I learn about focus/energy)',(800,930,1383,1205),'Large bordered box under a violet header.',{}),
 ('tomorrow_first_step','labelled dotted line',(800,1210,1383,1232),'One labelled dotted line.',{}),
],
20: [
 ('month_year_strip','plain thin month names + 1-31 (no colour)',(85,85,665,135),'Light grey month names with the day numbers beneath, no boxes.',{'sens+':'Colourless and quiet.'}),
 ('time_blocks','hour labels (7-9) + ruled lines',(85,200,365,810),'Hours 7 through 9 down the left, each with a ruled line.',{'adhd+':'Hour lines without boxes are easy to ignore.'}),
 ('top_priorities','3 numbered ruled lines',(390,205,670,350),'"Priorities" label over lines numbered 1-3.',{}),
 ('todo_list','"lists": circle bullets on ruled lines',(390,355,670,810),'Header "lists" with a column of faint circle bullets on ruled lines.',{}),
 ('notes','full ruled right page',(825,70,1385,830),'Whole page ruled lines under the word notes.',{}),
],
21: [
 ('date_header','handwritten date + weekday in brackets',(10,5,200,40),'Month/day with the weekday in brackets.',{}),
 ('focus_box','memo box with goal for the day',(20,40,260,140),'Rounded box labelled Memo; one-line target written inside.',{}),
 ('productivity_rating','total time (hh:mm) over a heart',(285,5,395,110),'Large write-in of total study time.',{}),
 ('todo_list','2-column box checklist (8 rows)',(20,150,400,400),'Two columns of small checkboxes each with a handwritten task; highlighters underline.',{'inp':'checkbox'}),
 ('notes','free handwriting reflection area',(20,400,400,500),'Unlined area used for a short reflection.',{}),
 ('time_record','vertical 24h timeline coloured with highlighters',(410,5,600,545),'Hourly column 05-04; colour bars show when tasks happened; diagonal hatching marks sleep.',{'adhd+':'Colouring afterwards avoids pre-planning; blank is fine.','sens+':'Needs highlighters; pen shading works too.'}),
],
}
