"""Vector line-drawing templates for the mocker, one per (element, variant_group).
Each template: k = drawing kind (see the renderer in site mocker), dw/dh = default size in dots, mw/mh = minimum size,
plus kind-specific parameters.  Labels are the wording used in the examples (hand-lettering stand-ins), editable in the mocker.
Sizes are in dots at the notebook's pitch (page 28 x 42 dots)."""
def t(k, dw, dh, mw=None, mh=None, **p):
    d = dict(k=k, dw=dw, dh=dh, mw=mw if mw is not None else 4, mh=mh if mh is not None else 2); d.update(p); return d
L = 'lines'
TEMPLATES = {
 # header
 'date_header|date write-in line': t('field', 14, 2, 8, 2, label='DATE', pos='left', slashes=True),
 'date_header|stacked DD / MM / YY boxes': t('stack', 6, 6, 5, 6, labels=['DD', 'MM', 'YY']),
 'focus_theme|short write-in line': t('field', 22, 3, 8, 2, label="THIS WEEK I'M FOCUSING ON", pos='above'),
 'focus_theme|boxed goal line': t('box', 26, 3, 10, 3, label='GOAL FOR THE WEEK:', inline=True),
 'focus_theme|sentence starter / frame': t('field', 26, 2, 12, 2, label='THIS WEEK WILL BE ______ BECAUSE ______', pos='left'),
 'month_year_strip|colour-coded strip': t('strip', 27, 3, 14, 3),
 'month_year_strip|plain strip': t('strip', 27, 3, 14, 3, plain=True),
 'quote_mantra|printed quote': t('quote', 22, 4, 10, 3),
 'quote_mantra|banner affirmation': t('pill', 24, 2, 8, 2, text='I CHOOSE INTENTION OVER PERFECTION.'),
 'week_header|printed date range + week number': t('headtext', 25, 2, 12, 2, text='NOV 27 — DEC 3', right='WEEK 49', rule=True),
 'week_header|title + write-in date': t('headtext', 25, 2, 12, 2, text='WEEKLY OVERVIEW', right='DATE: ______', rule=False),
 'week_header|title only': t('headtext', 25, 2, 10, 2, text='WEEKLY REFLECTION & GOALS', rule=True),
 'weekday_circles|letters only': t('wkdays', 8, 2, 7, 2, circles=False),
 'weekday_circles|letters over circles': t('wkdays', 8, 3, 7, 3, circles=True),
 # plan
 'top_priorities|3 numbered lines': t(L, 16, 8, 8, 4, label='TOP 3 PRIORITIES', bullet='num'),
 'top_priorities|3 checkbox lines': t(L, 16, 8, 8, 4, label='TOP 3 PRIORITIES', bullet='check'),
 'top_priorities|5+ numbered / bullet lines': t(L, 24, 12, 10, 4, label='IF I ONLY DID 5 THINGS THIS WEEK...', bullet='num'),
 'top_priorities|two open columns': t('table', 24, 8, 12, 4, heads=['PRIORITY TASKS', 'PLAY ACTIVITIES'], cols=[.5, .5], open=True),
 'top_priorities|panel with rating icons + reward': t(L, 26, 10, 14, 6, label='PRIORITIES', bullet='dot', rate=True, reward=True),
 'top_priorities|priority box with time': t('box', 12, 6, 8, 4, label='DAILY PRIORITY TASK', time=True),
 'focus_box|single titled box': t('box', 16, 6, 8, 4, label="TODAY'S FOCUS", fill=True),
 'focus_box|dotted goal lines': t(L, 14, 6, 8, 4, label='GOALS', bullet='none', rule='dotted'),
 'todo_list|bullet / numbered lines': t(L, 12, 16, 8, 4, label='TO DO', bullet='dot', rule='dotted', box=True),
 'todo_list|checkbox / circle lines': t(L, 14, 12, 8, 4, label='TO DO', bullet='circle', rule='dotted'),
 'todo_list|routine lines + completed boxes': t(L, 24, 12, 12, 4, label='MORNING ROUTINE', bullet='num', end='check'),
 'secondary_tasks|checkbox / dotted lines': t(L, 16, 12, 8, 4, label='OTHER TASKS', bullet='check', rule='dotted'),
 'secondary_tasks|optional numbered extras': t(L, 16, 10, 8, 4, label='GOT EXTRA TIME?', bullet='num', start=4),
 'secondary_tasks|tasks with sub-steps + icons': t(L, 26, 14, 14, 6, label='DO LATER', bullet='check', sub=True, rate=True, reward=True),
 'weekly_goals|3 numbered lines': t(L, 14, 9, 8, 4, label='WEEKLY GOALS', bullet='num', box=True),
 'focus_areas|titled column: header box + 8 circle-bullet lines (first 3 shaded)': t(L, 13, 16, 8, 6, label='', bullet='circle', rule='dotted', hbox=True, shade=3),
 'not_to_do|4 grey checkbox lines': t(L, 10, 10, 6, 4, label='NOT TO DO', bullet='check', rule='dotted', box=True),
 'event_organizer|two-column event / date table': t('table', 24, 12, 12, 6, heads=['EVENT', 'DATE'], cols=[.7, .3], title='IMPORTANT EVENTS / OCCASIONS'),
 'appointments|time + write-in lines': t(L, 14, 10, 8, 4, label='APPOINTMENTS', bullet='time'),
 'to_buy|checkbox list': t(L, 12, 12, 8, 4, label='TO BUY', bullet='check'),
 'people_to_connect|short list': t(L, 16, 10, 8, 4, label='PEOPLE TO CONNECT WITH', bullet='circle'),
 'one_three_five|1 focus task': t(L, 24, 8, 12, 4, label='1 FOCUS TASK', bullet='check', rate=True, reward=True),
 'one_three_five|3 support tasks': t(L, 24, 14, 12, 6, label='3 SUPPORT TASKS', bullet='check', sub=True, rate=True, reward=True),
 'one_three_five|5 tiny wins': t(L, 24, 12, 12, 4, label='5 TINY WINS', bullet='circle', rate=True),
 'sorted_task_hub|3x4 colour-coded zones of 5 checkbox lines each': t('cells', 27, 36, 15, 20, cols=3, rows=4, lines=True,
     labels=['I NEED TO CALL', 'I NEED TO EMAIL', 'I NEED TO TEXT', 'I NEED TO DO TODAY', 'APPOINTMENTS', 'I NEED TO FOLLOW UP ON', 'I NEED TO DO SOON', 'I NEED TO SCHEDULE', 'I NEED TO RESEARCH', "TODAY'S WINS", 'I NEED TO BUY', 'RANDOM THOUGHTS']),
 # schedule
 'week_at_a_glance|day boxes with header bars': t('daygrid', 27, 24, 14, 12),
 'week_at_a_glance|stacked day rows': t('dayrows', 26, 34, 14, 16),
 'week_at_a_glance|ruled day columns': t('daycols', 54, 24, 24, 12),
 'time_blocks|time | task | tick table': t('table', 16, 22, 10, 6, heads=['TIME', 'TASK', ''], cols=[.22, .66, .12], rowH=2, tick=True),
 'time_blocks|vertical checkbox column': t(L, 12, 26, 6, 6, label='', bullet='check', rule='dotted', rowH=1, small=True, start_label='START'),
 'time_blocks|hour-ruled lines': t(L, 11, 24, 6, 6, label='SCHEDULE', bullet='hour', start=7, rowH=2),
 'time_blocks|flexible time column': t('axis', 12, 24, 6, 6, label='DAILY PLAN', hours=False),
 'day_part_schedule|morning / afternoon / evening / night circle lines': t('sections', 14, 28, 8, 10, labels=['MORNING', 'AFTERNOON', 'EVENING', 'NIGHT'], split=[3, 3, 2, 1]),
 'time_record|vertical 24h timeline coloured with highlighters': t('axis', 8, 26, 6, 12, label='TIME RECORD', hours=True, from_h=5),
 'monthly_calendar|stacked mini month grids (Mon start)': t('calendar', 10, 9, 7, 7),
 'clock_planner|12-hour clock face to shade': t('clock', 8, 8, 6, 6),
 # track
 'energy_tracker|segment bar to colour': t('segbar', 16, 3, 8, 3, segs=5, label='ENERGY'),
 'energy_tracker|notes by time of day': t(L, 12, 10, 8, 6, label='ENERGY & PATTERNS', bullet='none', labels=['Morning:', 'Afternoon:', 'Evening:']),
 'habit_tracker|named rows x 7-day checkboxes': t('grid', 24, 10, 14, 6, label='HABIT TRACKER', cell='box'),
 'habit_tracker|named rows x 7-day dots / circles': t('grid', 24, 10, 14, 6, label='HABIT TRACKER', cell='circle'),
 'habit_tracker|secondary habits + reflection line': t(L, 23, 10, 12, 4, label='SECONDARY HABITS', bullet='check', labels=['Comfort zone', 'Play activity', 'Practice altruism', 'Nurture relationship']),
 'habit_tracker|rows with tick column (no days)': t(L, 16, 10, 8, 4, label='HABIT TRACKER', bullet='none', end='check'),
 'health_fitness|short checkbox list': t('checkrow', 18, 3, 10, 2, label='BODY CHECK', labels=['WATER', 'MEAL', 'MEDS', 'MOVE']),
 'meals|per-meal fields': t(L, 16, 10, 8, 4, label='MEALS', bullet='none', labels=['Breakfast:', 'Lunch:', 'Dinner:', 'Snacks:']),
 'meals|single line': t('field', 14, 3, 8, 2, label='MEALS', pos='left'),
 'mood_tracker|circular wheel': t('wheel', 14, 14, 10, 10),
 'mood_tracker|colour boxes + faces': t('boxfaces', 18, 4, 12, 4, n=6, label='(COLOUR) SCALE'),
 'mood_tracker|single face': t('faces', 10, 3, 4, 2, n=1, label='MOOD'),
 'mood_tracker|open band': t('box', 24, 4, 10, 3, label='MOOD & ENERGY CHECK-IN', fill=True),
 'productivity_rating|open score row': t('field', 16, 3, 8, 2, label='PRODUCTIVITY', pos='left'),
 'productivity_rating|total time': t('box', 9, 5, 6, 4, label='TOTAL TIME', hint='__ : __'),
 'self_care_grid|4x3 icon grid with corner checkboxes': t('iconcells', 16, 9, 8, 6, cols=4, rows=3),
 'sleep_times|slept / woke tinted boxes': t('boxfields', 14, 2, 8, 2, labels=['SLEPT', 'WOKE']),
 'water_tracker|row of drops / circles': t('icons', 12, 3, 6, 2, icon='drop', n=8, label='WATER'),
 'weather|row of 5 weather icons': t('icons', 10, 2, 6, 2, icon='weather', n=5),
 # reflect
 'challenge|tinted header + one-line challenge box': t('box', 24, 4, 10, 3, label='INTENTIONAL CHALLENGE', fill=True, hint='Say one kind thing to yourself every morning.'),
 'challenge|small / big challenge lines': t(L, 24, 8, 12, 4, label='COMFORT ZONE CHALLENGES', bullet='none', labels=['Small:', 'Big:']),
 'challenge|4 secondary-habit options with circle + how line': t(L, 12, 16, 8, 6, label='TODAY, I AM GOING TO:', bullet='circle', sub=True),
 'end_of_day_check|three kind options': t(L, 14, 8, 10, 4, label='END-OF-DAY', bullet='check', labels=['ROCKED IT', 'SATISFACTORY', 'BETTER DAYS ARE COMING']),
 'end_of_day_check|pre-sleep ritual line': t('field', 23, 3, 10, 2, label='PRE-SLEEP RITUAL(S)', pos='left', end='DONE ☐'),
 'feelings_check|row of 5 emotion faces + other': t('faces', 24, 3, 10, 3, n=5, label='HOW I\'M FEELING', labels=['HAPPY', 'EXCITED', 'LOVED', 'STRESSED', 'TIRED']),
 'gratitude|boxed list': t('box', 16, 8, 8, 4, label="I'M GRATEFUL FOR", dash=3),
 'gratitude|tick-box checklist': t(L, 10, 9, 6, 4, label='GRATEFUL FOR', bullet='check', labels=['Food', 'Water', 'Clothing', 'Bed', 'Shelter'], rowH=1),
 'gratitude|numbered lines': t(L, 23, 8, 12, 4, label='THIS EVENING I FEEL GRATEFUL FOR...', bullet='num'),
 'highlight_of_day|boxed': t('box', 16, 4, 8, 3, label='HIGHLIGHT OF THE DAY:'),
 'highlight_of_day|one line': t('field', 22, 3, 8, 2, label="TODAY'S HIGHLIGHT", pos='above', hint='big or small'),
 'identity_statement|prompted open box': t('box', 14, 7, 8, 4, label='IDENTITY STATEMENT', hint='I am the type of person that...'),
 'improve_next|ruled lines': t(L, 24, 6, 10, 4, label='WHAT WILL YOU CONTINUE OR CHANGE?', bullet='none'),
 'improve_next|checkbox rows': t(L, 14, 8, 8, 4, label="HOW I'LL IMPROVE NEXT WEEK", bullet='check'),
 'improve_next|open box': t('box', 24, 6, 10, 4, label='WHAT ACTIONS CAN I TAKE TO MAKE NEXT WEEK BETTER?'),
 'improve_next|two-column went well | improve': t('table', 24, 8, 12, 4, heads=['WHAT WENT WELL TODAY?', 'HOW CAN I IMPROVE TOMORROW?'], cols=[.5, .5], open=True),
 'leave_behind|boxed dash list (leave behind)': t('box', 12, 8, 8, 4, label='I WANT TO LEAVE BEHIND', dash=3),
 'lessons_learned|checkbox / numbered lines': t(L, 14, 8, 8, 4, label='LESSONS LEARNED THIS WEEK', bullet='check'),
 'lessons_learned|open box': t('box', 24, 7, 10, 4, label='WEEKLY INSIGHTS', fill=True),
 'life_area_goals|6 shaded boxes in 2x3 (personal, career, ...)': t('cells', 26, 13, 14, 8, cols=2, rows=3, labels=['PERSONAL', 'CAREER', 'RELATIONSHIPS', 'HEALTH & FITNESS', 'SPIRITUAL', 'FINANCIAL'], fill=True),
 'mood_impact|3-column positive / neutral / negative box': t('table', 22, 16, 14, 8, heads=['POSITIVE', 'NEUTRAL', 'NEGATIVE'], cols=[1/3, 1/3, 1/3], open=True, title='WHAT IMPACTED YOUR MOOD?', faces=True),
 'priority_review|score / percent field': t(L, 24, 8, 12, 4, label='HOW FAR DID YOU GET ON YOUR WEEKLY PRIORITIES?', bullet='none', end='%'),
 'resistance_check|ANT / resistance prompts': t(L, 23, 8, 12, 4, label='WHAT ANT(S) SHOWED UP TODAY?', bullet='none', labels=['', 'Replacement PET(s):']),
 'review_prompts|prompt + open space': t('box', 24, 8, 10, 4, label='PROMPT / QUESTION', hint='write the question you want to answer', plain=True),
 'review_prompts|prompt + ruled lines': t(L, 24, 8, 12, 4, label='PROMPT / QUESTION', bullet='none'),
 'review_prompts|two-column prompt': t('table', 24, 8, 12, 4, heads=['WHAT HABITS ARE GETTING EASIER?', 'WHAT DID I STRUGGLE WITH?'], cols=[.5, .5], open=True),
 'reward|weekly reward + when box': t('field', 20, 3, 10, 2, label='WEEKLY REWARD', pos='left', end='WHEN ☐'),
 'tomorrow_first_step|labelled dotted line': t('field', 24, 2, 10, 2, label="TOMORROW'S FIRST STEP:", pos='left', dotted=True),
 'wins|numbered lines': t(L, 23, 8, 12, 4, label='MY TOP 3 WINS', bullet='num'),
 'wins|checkbox rows': t(L, 14, 8, 8, 4, label="THIS WEEK'S WINS", bullet='check'),
 'wins|open / tinted box': t('box', 23, 5, 10, 3, label="TODAY'S WIN (BIG OR SMALL)", fill=True),
 # capture
 'brain_dump|open box with label': t('box', 16, 8, 8, 4, label='BRAIN DUMP', hint='no sorting, no judging'),
 'brain_dump|ruled lines': t(L, 22, 14, 10, 4, label='NOTES / BRAIN RELEASE', bullet='none'),
 'notes|boxed area': t('box', 14, 8, 6, 3, label='NOTES'),
 'notes|ruled page / lines': t(L, 26, 36, 10, 6, label='NOTES', bullet='none', rowH=2),
 'notes|dotted free space': t('dots', 20, 10, 6, 4, label='FREE SPACE'),
 'notes|unlined area': t('box', 24, 8, 8, 3, label='', plain=True, dashed=True),
 # decorative
 'banner|colour label tab': t('pill', 8, 2, 4, 2, text='LABEL'),
 'color_key|3-part colour key (priorities / appointments / to buy)': t('legend', 26, 2, 14, 2, items=['TOP PRIORITIES', 'APPOINTMENTS', 'TO BUY']),
}
